### ISSUE TITLE
App crashes when zip-output-folder is root directory. Needs more errorhandling

### ISSUE THREAD

**Issue by chrisbarth01** [k3b/ToGoZip#20]
#### Expected behavior 
I expected the app to save the LogCat to file as I had earlier selected the storage location. 

---

#### Actual behavior 
Immediately I clicked on the 'Save LogCat to file' option, the app crashed

---

#### How to reproduce 
- Download, install and launch the latest version of the app
- Select storage location 
- Scroll down to the end
- Click on the 'Save LogCat to file' option
- Observe the crash.

---

Device: Gionee f100s 
Android version: v6.0
App version: v2.0.19.190413

---

#### Recording of the bug
- https://youtu.be/Jwe6rbS0ST4

---

**Comment by k3b** [comment]
hello @chrisbarth01 . thanks for the error report. without an errorlog i have no clue what has happened.

To help me analyse the problem: can you open the togozip-settings and check " [X] Debug Mode".
After the crash there is hopefully the error protocol in the text clipboard.

can you past the text in a text editor and attach it to this ticket?

**Comment by chrisbarth01** [comment]
It's so unfortunate that I can't even open the settings which I think is in the three dots at the top of the screen because the app still crashes (I already reported that too). However, I don't think that it's permission issue because immediately I launch the app, it asked me to grant storage permission and I granted the app permission to my device's internal storage.

**Comment by k3b** [comment]
i just updated myanswer: Can you try if it works if you change to some subfolder?

**Comment by chrisbarth01** [comment]
I just resolved it. The subfolder worked!

**Comment by k3b** [comment]
i just checked. the app crashes if i try to write to root without error-log and without log in clipboard. i have to fix this.

i keep this issue open to remind me to improve error-handling for this use case. 

thanks again for reporting.

**Comment by k3b** [comment]
fixed. Will be available in v2.0.20.190606 which i have just released
